apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: javaapp

images:
- name: javaapp
  newName: matheusnb/argocd
  newTag: 511812969d364ee0bc34ac1eaaee605164ed71da
